# Упражнение 02

## Первый пункт

Скачай и прочитай CSV-файл, указав ID в качестве индексного столбца.

In [1]:
import pandas as pd

df = pd.read_csv("data/auto.csv", index_col="ID", sep=",")

## Второй пункт

Подсчитай число наблюдений с помощью метода count().

In [2]:
df.count()

CarNumber       931
Make_n_model    931
Refund          914
Fines           869
History          82
dtype: int64

## Третий пункт 

Удали дубликаты, учитывая только столбцы CarNumber, Make_n_Model и Fines.
Из двух одинаковых наблюдений оставляй последнее.
Ещё раз проверь количество наблюдений.

In [3]:
df = df.drop_duplicates(subset=["CarNumber", "Make_n_model", "Fines"], keep="last")
df.count()

CarNumber       725
Make_n_model    725
Refund          713
Fines           665
History          65
dtype: int64

## Четвертый пункт

Поработай с пропущенными значениями.
Посмотри, сколько пропусков в каждом столбце.
Удали все столбцы с более чем 500 пропусками, используя аргумент thresh. Проверь число пропусков в каждом столбце.
Замени все пропуски в столбце Refund предыдущим значением в этом столбце (используй аргумент method) и проверь число пропусков.
Замени все пропуски в столбце Fines средним значением этого столбца (не учитывая NA/NULL при вычислении среднего). Снова проверь число пропусков.

In [4]:
df.isna().sum() # Смотрим сколько пропусков в каждом столбце

CarNumber         0
Make_n_model      0
Refund           12
Fines            60
History         660
dtype: int64

In [5]:
df = df.dropna(axis="columns", thresh=len(df)-500) # Удаляем столбцы с пропусками > 500
df.isna().sum()

CarNumber        0
Make_n_model     0
Refund          12
Fines           60
dtype: int64

In [6]:
df["Refund"] = df["Refund"].ffill() # Заполняем пустые значения предыдущими
df["Refund"].isna().sum()

np.int64(0)

In [7]:
mean_fines = df["Fines"].mean() # Среднее значение
df["Fines"] = df["Fines"].fillna(mean_fines)
df["Fines"].isna().sum()

np.int64(0)

## Пятый пункт 

Раздели и распарьсь марку и модель.
Используй apply и для разбиения, и для извлечения значений в новые столбцы Make и Model.
Удали столбец Make_n_Model.
Сохрани датафрейм в файл auto.json в формате ниже:
[{"CarNumber":"Y163O8161RUS","Refund":2.0,"Fines":3200.0,"Make":"Ford",
"Model":"Focus"},
{"CarNumber":"E432XX77RUS","Refund":1.0,"Fines":6500.0,"Make":"Toyota",
"Model":"Camry"}]

In [8]:
makenmodel = df["Make_n_model"].apply(
    lambda x: x.split()
)

df["Make"] = makenmodel.apply(
    lambda x: x[0]
)

df["Model"] = makenmodel.apply(
    lambda x: x[1] if len(x) > 1 else None
)

df[["Make_n_model", "Make", "Model"]]

       Make_n_model    Make    Model
ID
0        Ford Focus    Ford    Focus
1      Toyota Camry  Toyota    Camry
2        Ford Focus    Ford    Focus
3        Ford Focus    Ford    Focus
5        Ford Focus    Ford    Focus
..              ...     ...      ...
926      Ford Focus    Ford    Focus
927      Ford Focus    Ford    Focus
928      Ford Focus    Ford    Focus
929      Ford Focus    Ford    Focus
930  Toyota Corolla  Toyota  Corolla

[725 rows x 3 columns]

In [9]:
df = df.drop(columns=["Make_n_model"])
df

        CarNumber  Refund         Fines    Make    Model
ID
0    Y163O8161RUS     2.0   3200.000000    Ford    Focus
1     E432XX77RUS     1.0   6500.000000  Toyota    Camry
2     7184TT36RUS     1.0   2100.000000    Ford    Focus
3    X582HE161RUS     2.0   2000.000000    Ford    Focus
5    92918M178RUS     1.0   5700.000000    Ford    Focus
..            ...     ...           ...     ...      ...
926  Y163O8161RUS     2.0   1600.000000    Ford    Focus
927  M0309X197RUS     1.0  22300.000000    Ford    Focus
928  O673E8197RUS     2.0    600.000000    Ford    Focus
929  8610T8154RUS     1.0   2000.000000    Ford    Focus
930  H419XE197RUS     2.0   8594.586466  Toyota  Corolla

[725 rows x 5 columns]

In [10]:
df.to_json(
    "data/auto.json",
    orient="records"
) # Сохраняем в JSON, вариант который в задании - records