# Упражнение 00

## Первый пункт
read_csv:
Отфильтруй строки с индексами 2 и 3 с помощью аргумента skiprows - мы знаем, что эти наблюдения были фейковыми.
Отфильтруй последние две строки «хвоста» с помощью аргумента skipfooter - они тоже фейковые.
Задай имена столбцов: datetime, user.
Используй datetime как индексный столбец.

In [14]:
import pandas as pd

df = pd.read_csv("data/feed-views.log",
    sep="\t",
    names=["datetime", "user"],
    skiprows=[2, 3],
    skipfooter=2,
    engine="python",
    index_col="datetime"
)

## Второй пункт

Переименуй datetime в date_time

In [15]:
df.index.name = "date_time"

## Третий пункт
Используй в качестве разделителя символ ';'.
Сохрани в файл feed-views-semicolon.log.

In [16]:
df.to_csv("data/feed-views-semicolon.log", sep=";")

## Проверка результата

In [17]:
df.head()

                              user
date_time
2020-04-17 12:01:08.463179   artem
2020-04-17 12:01:23.743946   artem
2020-04-17 12:35:52.735016   artem
2020-04-17 12:36:21.401412  oksana
2020-04-17 12:36:22.023355  oksana

In [18]:
df.tail()

                                 user
date_time
2020-05-21 16:36:40.915488  ekaterina
2020-05-21 17:49:36.429237      maxim
2020-05-21 18:45:20.441142  valentina
2020-05-21 23:03:06.457819      maxim
2020-05-21 23:23:49.995349      pavel