# Упражнение 01

## Первый пункт

Создай датафрейм с названием views с двумя столбцами datetime и user, прочитав файл feed-views.log.
Приведи столбец datetime к типу datetime64[ns] (dtype).
Извлеки из datetime год, месяц, день, час, минуту и секунду в новые столбцы.

In [63]:
import pandas as pd

views = pd.read_csv('data/feed-views.log', sep="\t", names=["datetime", "user"])

views["datetime"] = pd.to_datetime(views["datetime"])
views["datetime"].dtype # Проверка типа столбца

views["year"] = views["datetime"].dt.year
views["month"] = views["datetime"].dt.month
views["day"] = views["datetime"].dt.day
views["hour"] = views["datetime"].dt.hour
views["minute"] = views["datetime"].dt.minute
views["second"] = views["datetime"].dt.second

## Второй пункт

Создай новый столбец daytime.
Присваивай значение времени суток, если час попадает в заданный интервал (например, «afternoon», если час > 11 и ≤ 17).
0-3:59 = night, 4-6:59 = early morning, 7-10:59 = morning, 11-16:59 = afternoon, 17-19:59 = early evening, 20-23:59 = evening.
Для решения подзадачи используй метод cut.
Назначь столбец user индексом.

In [64]:
bins = [0,4,7,11,17,20,24]
labels = ['night','early morning','morning','afternoon','early evening','evening']

views["daytime"] = pd.cut(views["hour"], bins=bins, labels=labels, right=False)

views = views.set_index("user")

views

,datetime,year,month,day,hour,minute,second,daytime
user,,,,,,,,
artem,2020-04-17 12:01:08.463179,2020,4,17,12,1,8,afternoon
artem,2020-04-17 12:01:23.743946,2020,4,17,12,1,23,afternoon
artem,2020-04-17 12:27:30.646665,2020,4,17,12,27,30,afternoon
artem,2020-04-17 12:35:44.884757,2020,4,17,12,35,44,afternoon
artem,2020-04-17 12:35:52.735016,2020,4,17,12,35,52,afternoon
...,...,...,...,...,...,...,...,...
valentina,2020-05-21 18:45:20.441142,2020,5,21,18,45,20,early evening
maxim,2020-05-21 23:03:06.457819,2020,5,21,23,3,6,evening
pavel,2020-05-21 23:23:49.995349,2020,5,21,23,23,49,evening
artem,2020-05-21 23:49:22.386789,2020,5,21,23,49,22,evening
artem,2020-05-22 10:36:14.662600,2020,5,22,10,36,14,morning

## Третий пункт 

Посчитай количество элементов в датафрейме.
Используй метод count().
Посчитай число элементов в каждой категории времени суток с помощью value_counts().

In [65]:
views.count()

datetime    1076
year        1076
month       1076
day         1076
hour        1076
minute      1076
second      1076
daytime     1076
dtype: int64

In [66]:
views["daytime"].value_counts()

daytime
evening          509
afternoon        252
early evening    145
night            129
morning           36
early morning      5
Name: count, dtype: int64

## Четвертый пункт

Отсортируй значения в датафрейме одновременно по часам, минутам и секундам по возрастанию (не по одному столбцу по очереди).

In [67]:
views.sort_values(by=["hour", "minute","second"])

,datetime,year,month,day,hour,minute,second,daytime
user,,,,,,,,
valentina,2020-05-15 00:00:13.222265,2020,5,15,0,0,13,night
valentina,2020-05-15 00:01:05.153738,2020,5,15,0,1,5,night
pavel,2020-05-12 00:01:27.764025,2020,5,12,0,1,27,night
pavel,2020-05-12 00:01:38.444917,2020,5,12,0,1,38,night
pavel,2020-05-12 00:01:55.395042,2020,5,12,0,1,55,night
...,...,...,...,...,...,...,...,...
artem,2020-05-21 23:49:22.386789,2020,5,21,23,49,22,evening
anatoliy,2020-05-09 23:53:55.599821,2020,5,9,23,53,55,evening
pavel,2020-05-09 23:54:54.260791,2020,5,9,23,54,54,evening
valentina,2020-05-14 23:58:56.754866,2020,5,14,23,58,56,evening
alexander,2020-05-14 23:59:38.758438,2020,5,14,23,59,38,evening

## Пятый пункт

Вычисли минимум и максимум для часов и моду для категорий daytime.
Найди максимальный час для строк, где время суток - night.
Найди минимальный час для строк, где время суток - morning.
Дополнительно узнай, кто посещал страницу в эти часы, и приведи один пример.
Вычисли моду для часа и для daytime.

In [68]:
views["hour"].min()

np.int32(0)

In [69]:
views["hour"].max()

np.int32(23)

In [70]:
views.loc[views["daytime"] == "night", ["hour"]].max()
views.loc[views["daytime"] == "night", ["hour"]].index[0]

'artem'

In [71]:
views.loc[views["daytime"] == "morning", ["hour"]].min()
views.loc[views["daytime"] == "morning", ["hour"]].index[0]

'konstantin'

In [72]:
views["hour"].mode()
views["daytime"].mode()

0    evening
Name: daytime, dtype: category
Categories (6, str): ['night' < 'early morning' < 'morning' < 'afternoon' < 'early evening' < 'evening']

## Шестой пункт

Покажи три самых ранних и три самых поздних часа дня и соответствующие имена пользователей, используя nsmalles() и nlargest().

In [73]:
views.nlargest(3, 'hour')["hour"]

user
konstantin    23
artem         23
artem         23
Name: hour, dtype: int32

In [74]:
views.nsmallest(3, 'hour')["hour"]

user
artem         0
konstantin    0
konstantin    0
Name: hour, dtype: int32

## Седьмой пункт

Используй метод describe() для получения базовой статистики по столбцам.
Чтобы найти самый популярный интервал посещений, вычисли интерквартильный размах для часа: извлеки нужные значения из результата describe() и сохрани их в переменную iqr.

In [76]:
statistics = views.describe()
q1 = statistics.loc["25%","hour"]
q3 = statistics.loc["75%","hour"]

IQR = q3 - q1

IQR

np.float64(9.0)